#!/usr/bin/env bash

# Copyright (C) 2020 Andreas Füglistaler <andreas.fueglistaler@epfl.ch>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

#set -e
cd `dirname $0`

ediff() {
   diff -q - $1 $2 1>&2 
}

for f in input/*.pdb;do
	name=${f#input/}
	name=${name%.pdb}

	../bin/copy $f | ediff output/${name}_copy.pdb 

	../bin/renumber $f | ediff output/${name}_renumber.pdb 
	../bin/renumber -s 10 $f | ediff output/${name}_renumber_10.pdb 

	../bin/translate -x100 -c Z $f | ediff output/${name}_copy.pdb 
	../bin/translate -x100 $f | ediff output/${name}_translate_x100.pdb 
	../bin/translate -y-23 $f | ediff output/${name}_translate_y-23.pdb 
	../bin/translate -z333 $f | ediff output/${name}_translate_z333.pdb 
	../bin/translate -x1 -y2 -z3 $f | ediff output/${name}_translate_x1_y2_z3.pdb 
	../bin/extract -c A $f | ediff output/${name}_A.pdb

done

f=input/3zev.pdb
../bin/translate -y 23 -c BD $f | ediff output/${name}_translate_y23_BD.pdb 
../bin/extract -c BD $f | ediff output/${name}_BD.pdb
../bin/extract -c DCBA -i ABCD $f | ediff output/${name}_DCBA_ABCD.pdb
