#!/usr/bin/env bash

# Copyright (C) 2020 Andreas Füglistaler <andreas.fueglistaler@epfl.ch>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

#set -e
cd `dirname $0`

ediff() {
   diff -q - $1 $2 1>&2 
}

for f in input/*.pdb;do
	name=${f#input/}
	name=${name%.pdb}

	../src/copy.d $f | ediff output/${name}_copy.pdb 
	../src/renumber.d $f | ediff output/${name}_renumber.pdb 
	../src/renumber.d -s 10 $f | ediff output/${name}_renumber_10.pdb 

done
